/* jce - 2.6.8 | 2017-02-01 | http://www.joomlacontenteditor.net | Copyright (C) 2006 - 2017 Ryan Demmer. All rights reserved | GNU/GPL Version 2 or later - http://www.gnu.org/licenses/gpl-2.0.html */
function renderCharMapHTML() {
    var i, charsPerRow = 19,
        html = '<ul class="charmap">',
        cols = -1;
    for (i = 0; i < charmap.length; i++) 1 == charmap[i][2] && (cols++, html += '<li><a onmouseover="previewChar(\'' + charmap[i][1] + '\',\'' + charmap[i][0] + '\',\'' + charmap[i][3] + '\');" onfocus="previewChar(\'' + charmap[i][1] + '\',\'' + charmap[i][0] + '\',\'' + charmap[i][3] + '\');" onclick="insertChar(\'' + charmap[i][1] + '\')"><span class="' + charmap[i][1] + '"></span></a></li>');
    
    return html += "</ul>"
}

function insertChar(chr) {
    tinyMCEPopup.execCommand("mceInsertContent", !1, '<span class="' + chr + '"></span>'), tinyMCEPopup.isWindow && window.focus(), tinyMCEPopup.editor.focus(), tinyMCEPopup.close()
}

function previewChar(codeA, codeB, codeN) {

    var elmV = document.getElementById("codeV"),
        elmN = document.getElementById("codeN");
				
    	elmV.innerHTML = '<span class="'+codeA+'"></span>'
			elmN.innerHTML = codeN
			
}
var charmap = [
    ['&#xf000', 'fa fa-glass', 1, ' glass'],
    ['&#xf001', 'fa fa-music', 1, ' music'],
    ['&#xf002', 'fa fa-search', 1, ' search'],
    ['&#xf003', 'fa fa-envelope-o', 1, ' envelope o'],
    ['&#xf004', 'fa fa-heart', 1, ' heart'],
    ['&#xf005', 'fa fa-star', 1, ' star'],
    ['&#xf006', 'fa fa-star-o', 1, ' star o'],
    ['&#xf007', 'fa fa-user', 1, ' user'],
    ['&#xf008', 'fa fa-film', 1, ' film'],
    ['&#xf009', 'fa fa-th-large', 1, ' th large'],
    ['&#xf00a', 'fa fa-th', 1, ' th'],
    ['&#xf00b', 'fa fa-th-list', 1, ' th list'],
    ['&#xf00c', 'fa fa-check', 1, ' check'],
    ['&#xf00d', 'fa fa-times', 1, ' times'],
    ['&#xf00e', 'fa fa-search-plus', 1, ' search plus'],
    ['&#xf010', 'fa fa-search-minus', 1, ' search minus'],
    ['&#xf011', 'fa fa-power-off', 1, ' power off'],
    ['&#xf012', 'fa fa-signal', 1, ' signal'],
    ['&#xf013', 'fa fa-cog', 1, ' cog'],
    ['&#xf014', 'fa fa-trash-o', 1, ' trash o'],
    ['&#xf015', 'fa fa-home', 1, ' home'],
    ['&#xf016', 'fa fa-file-o', 1, ' file o'],
    ['&#xf017', 'fa fa-clock-o', 1, ' clock o'],
    ['&#xf018', 'fa fa-road', 1, ' road'],
    ['&#xf019', 'fa fa-download', 1, ' download'],
    ['&#xf01a', 'fa fa-arrow-circle-o-down', 1, ' arrow circle o down'],
    ['&#xf01b', 'fa fa-arrow-circle-o-up', 1, ' arrow circle o up'],
    ['&#xf01c', 'fa fa-inbox', 1, ' inbox'],
    ['&#xf01d', 'fa fa-play-circle-o', 1, ' play circle o'],
    ['&#xf01e', 'fa fa-repeat', 1, ' repeat'],
    ['&#xf021', 'fa fa-refresh', 1, ' refresh'],
    ['&#xf022', 'fa fa-list-alt', 1, ' list alt'],
    ['&#xf023', 'fa fa-lock', 1, ' lock'],
    ['&#xf024', 'fa fa-flag', 1, ' flag'],
    ['&#xf025', 'fa fa-headphones', 1, ' headphones'],
    ['&#xf026', 'fa fa-volume-off', 1, ' volume off'],
    ['&#xf027', 'fa fa-volume-down', 1, ' volume down'],
    ['&#xf028', 'fa fa-volume-up', 1, ' volume up'],
    ['&#xf029', 'fa fa-qrcode', 1, ' qrcode'],
    ['&#xf02a', 'fa fa-barcode', 1, ' barcode'],
    ['&#xf02b', 'fa fa-tag', 1, ' tag'],
    ['&#xf02c', 'fa fa-tags', 1, ' tags'],
    ['&#xf02d', 'fa fa-book', 1, ' book'],
    ['&#xf02e', 'fa fa-bookmark', 1, ' bookmark'],
    ['&#xf02f', 'fa fa-print', 1, ' print'],
    ['&#xf030', 'fa fa-camera', 1, ' camera'],
    ['&#xf031', 'fa fa-font', 1, ' font'],
    ['&#xf032', 'fa fa-bold', 1, ' bold'],
    ['&#xf033', 'fa fa-italic', 1, ' italic'],
    ['&#xf034', 'fa fa-text-height', 1, ' text height'],
    ['&#xf035', 'fa fa-text-width', 1, ' text width'],
    ['&#xf036', 'fa fa-align-left', 1, ' align left'],
    ['&#xf037', 'fa fa-align-center', 1, ' align center'],
    ['&#xf038', 'fa fa-align-right', 1, ' align right'],
    ['&#xf039', 'fa fa-align-justify', 1, ' align justify'],
    ['&#xf03a', 'fa fa-list', 1, ' list'],
    ['&#xf03b', 'fa fa-outdent', 1, ' outdent'],
    ['&#xf03c', 'fa fa-indent', 1, ' indent'],
    ['&#xf03d', 'fa fa-video-camera', 1, ' video camera'],
    ['&#xf03e', 'fa fa-picture-o', 1, ' picture o'],
    ['&#xf040', 'fa fa-pencil', 1, ' pencil'],
    ['&#xf041', 'fa fa-map-marker', 1, ' map marker'],
    ['&#xf042', 'fa fa-adjust', 1, ' adjust'],
    ['&#xf043', 'fa fa-tint', 1, ' tint'],
    ['&#xf044', 'fa fa-pencil-square-o', 1, ' pencil square o'],
    ['&#xf045', 'fa fa-share-square-o', 1, ' share square o'],
    ['&#xf046', 'fa fa-check-square-o', 1, ' check square o'],
    ['&#xf047', 'fa fa-arrows', 1, ' arrows'],
    ['&#xf048', 'fa fa-step-backward', 1, ' step backward'],
    ['&#xf049', 'fa fa-fast-backward', 1, ' st backward'],
    ['&#xf04a', 'fa fa-backward', 1, ' backward'],
    ['&#xf04b', 'fa fa-play', 1, ' play'],
    ['&#xf04c', 'fa fa-pause', 1, ' pause'],
    ['&#xf04d', 'fa fa-stop', 1, ' stop'],
    ['&#xf04e', 'fa fa-forward', 1, ' forward'],
    ['&#xf050', 'fa fa-fast-forward', 1, ' st forward'],
    ['&#xf051', 'fa fa-step-forward', 1, ' step forward'],
    ['&#xf052', 'fa fa-eject', 1, ' eject'],
    ['&#xf053', 'fa fa-chevron-left', 1, ' chevron left'],
    ['&#xf054', 'fa fa-chevron-right', 1, ' chevron right'],
    ['&#xf055', 'fa fa-plus-circle', 1, ' plus circle'],
    ['&#xf056', 'fa fa-minus-circle', 1, ' minus circle'],
    ['&#xf057', 'fa fa-times-circle', 1, ' times circle'],
    ['&#xf058', 'fa fa-check-circle', 1, ' check circle'],
    ['&#xf059', 'fa fa-question-circle', 1, ' question circle'],
    ['&#xf05a', 'fa fa-info-circle', 1, ' info circle'],
    ['&#xf05b', 'fa fa-crosshairs', 1, ' crosshairs'],
    ['&#xf05c', 'fa fa-times-circle-o', 1, ' times circle o'],
    ['&#xf05d', 'fa fa-check-circle-o', 1, ' check circle o'],
    ['&#xf05e', 'fa fa-ban', 1, ' ban'],
    ['&#xf060', 'fa fa-arrow-left', 1, ' arrow left'],
    ['&#xf061', 'fa fa-arrow-right', 1, ' arrow right'],
    ['&#xf062', 'fa fa-arrow-up', 1, ' arrow up'],
    ['&#xf063', 'fa fa-arrow-down', 1, ' arrow down'],
    ['&#xf064', 'fa fa-share', 1, ' share'],
    ['&#xf065', 'fa fa-expand', 1, ' expand'],
    ['&#xf066', 'fa fa-compress', 1, ' compress'],
    ['&#xf067', 'fa fa-plus', 1, ' plus'],
    ['&#xf068', 'fa fa-minus', 1, ' minus'],
    ['&#xf069', 'fa fa-asterisk', 1, ' asterisk'],
    ['&#xf06a', 'fa fa-exclamation-circle', 1, ' exclamation circle'],
    ['&#xf06b', 'fa fa-gift', 1, ' gift'],
    ['&#xf06c', 'fa fa-leaf', 1, ' leaf'],
    ['&#xf06d', 'fa fa-fire', 1, ' fire'],
    ['&#xf06e', 'fa fa-eye', 1, ' eye'],
    ['&#xf070', 'fa fa-eye-slash', 1, ' eye slash'],
    ['&#xf071', 'fa fa-exclamation-triangle', 1, ' exclamation triangle'],
    ['&#xf072', 'fa fa-plane', 1, ' plane'],
    ['&#xf073', 'fa fa-calendar', 1, ' calendar'],
    ['&#xf074', 'fa fa-random', 1, ' random'],
    ['&#xf075', 'fa fa-comment', 1, ' comment'],
    ['&#xf076', 'fa fa-magnet', 1, ' magnet'],
    ['&#xf077', 'fa fa-chevron-up', 1, ' chevron up'],
    ['&#xf078', 'fa fa-chevron-down', 1, ' chevron down'],
    ['&#xf079', 'fa fa-retweet', 1, ' retweet'],
    ['&#xf07a', 'fa fa-shopping-cart', 1, ' shopping cart'],
    ['&#xf07b', 'fa fa-folder', 1, ' folder'],
    ['&#xf07c', 'fa fa-folder-open', 1, ' folder open'],
    ['&#xf07d', 'fa fa-arrows-v', 1, ' arrows v'],
    ['&#xf07e', 'fa fa-arrows-h', 1, ' arrows h'],
    ['&#xf080', 'fa fa-bar-chart-o', 1, ' bar chart o'],
    ['&#xf081', 'fa fa-twitter-square', 1, ' twitter square'],
    ['&#xf082', 'fa fa-facebook-square', 1, ' cebook square'],
    ['&#xf083', 'fa fa-camera-retro', 1, ' camera retro'],
    ['&#xf084', 'fa fa-key', 1, ' key'],
    ['&#xf085', 'fa fa-cogs', 1, ' cogs'],
    ['&#xf086', 'fa fa-comments', 1, ' comments'],
    ['&#xf087', 'fa fa-thumbs-o-up', 1, ' thumbs o up'],
    ['&#xf088', 'fa fa-thumbs-o-down', 1, ' thumbs o down'],
    ['&#xf089', 'fa fa-star-half', 1, ' star half'],
    ['&#xf08a', 'fa fa-heart-o', 1, ' heart o'],
    ['&#xf08b', 'fa fa-sign-out', 1, ' sign out'],
    ['&#xf08c', 'fa fa-linkedin-square', 1, ' linkedin square'],
    ['&#xf08d', 'fa fa-thumb-tack', 1, ' thumb tack'],
    ['&#xf08e', 'fa fa-external-link', 1, ' external link'],
    ['&#xf090', 'fa fa-sign-in', 1, ' sign in'],
    ['&#xf091', 'fa fa-trophy', 1, ' trophy'],
    ['&#xf092', 'fa fa-github-square', 1, ' github square'],
    ['&#xf093', 'fa fa-upload', 1, ' upload'],
    ['&#xf094', 'fa fa-lemon-o', 1, ' lemon o'],
    ['&#xf095', 'fa fa-phone', 1, ' phone'],
    ['&#xf096', 'fa fa-square-o', 1, ' square o'],
    ['&#xf097', 'fa fa-bookmark-o', 1, ' bookmark o'],
    ['&#xf098', 'fa fa-phone-square', 1, ' phone square'],
    ['&#xf099', 'fa fa-twitter', 1, ' twitter'],
    ['&#xf09a', 'fa fa-facebook', 1, ' cebook'],
    ['&#xf09b', 'fa fa-github', 1, ' github'],
    ['&#xf09c', 'fa fa-unlock', 1, ' unlock'],
    ['&#xf09d', 'fa fa-credit-card', 1, ' credit card'],
    ['&#xf09e', 'fa fa-rss', 1, ' rss'],
    ['&#xf0a0', 'fa fa-hdd-o', 1, ' hdd o'],
    ['&#xf0a1', 'fa fa-bullhorn', 1, ' bullhorn'],
    ['&#xf0f3', 'fa fa-bell', 1, ' bell'],
    ['&#xf0a3', 'fa fa-certificate', 1, ' certificate'],
    ['&#xf0a4', 'fa fa-hand-o-right', 1, ' hand o right'],
    ['&#xf0a5', 'fa fa-hand-o-left', 1, ' hand o left'],
    ['&#xf0a6', 'fa fa-hand-o-up', 1, ' hand o up'],
    ['&#xf0a7', 'fa fa-hand-o-down', 1, ' hand o down'],
    ['&#xf0a8', 'fa fa-arrow-circle-left', 1, ' arrow circle left'],
    ['&#xf0a9', 'fa fa-arrow-circle-right', 1, ' arrow circle right'],
    ['&#xf0aa', 'fa fa-arrow-circle-up', 1, ' arrow circle up'],
    ['&#xf0ab', 'fa fa-arrow-circle-down', 1, ' arrow circle down'],
    ['&#xf0ac', 'fa fa-globe', 1, ' globe'],
    ['&#xf0ad', 'fa fa-wrench', 1, ' wrench'],
    ['&#xf0ae', 'fa fa-tasks', 1, ' tasks'],
    ['&#xf0b0', 'fa fa-filter', 1, ' filter'],
    ['&#xf0b1', 'fa fa-briefcase', 1, ' briefcase'],
    ['&#xf0b2', 'fa fa-arrows-alt', 1, ' arrows alt'],
    ['&#xf0c0', 'fa fa-users', 1, ' users'],
    ['&#xf0c1', 'fa fa-link', 1, ' link'],
    ['&#xf0c2', 'fa fa-cloud', 1, ' cloud'],
    ['&#xf0c3', 'fa fa-flask', 1, ' flask'],
    ['&#xf0c4', 'fa fa-scissors', 1, ' scissors'],
    ['&#xf0c5', 'fa fa-files-o', 1, ' files o'],
    ['&#xf0c6', 'fa fa-paperclip', 1, ' paperclip'],
    ['&#xf0c7', 'fa fa-floppy-o', 1, ' floppy o'],
    ['&#xf0c8', 'fa fa-square', 1, ' square'],
    ['&#xf0c9', 'fa fa-bars', 1, ' bars'],
    ['&#xf0ca', 'fa fa-list-ul', 1, ' list ul'],
    ['&#xf0cb', 'fa fa-list-ol', 1, ' list ol'],
    ['&#xf0cc', 'fa fa-strikethrough', 1, ' strikethrough'],
    ['&#xf0cd', 'fa fa-underline', 1, ' underline'],
    ['&#xf0ce', 'fa fa-table', 1, ' table'],
    ['&#xf0d0', 'fa fa-magic', 1, ' magic'],
    ['&#xf0d1', 'fa fa-truck', 1, ' truck'],
    ['&#xf0d2', 'fa fa-pinterest', 1, ' pinterest'],
    ['&#xf0d3', 'fa fa-pinterest-square', 1, ' pinterest square'],
    ['&#xf0d4', 'fa fa-google-plus-square', 1, ' google plus square'],
    ['&#xf0d5', 'fa fa-google-plus', 1, ' google plus'],
    ['&#xf0d6', 'fa fa-money', 1, ' money'],
    ['&#xf0d7', 'fa fa-caret-down', 1, ' caret down'],
    ['&#xf0d8', 'fa fa-caret-up', 1, ' caret up'],
    ['&#xf0d9', 'fa fa-caret-left', 1, ' caret left'],
    ['&#xf0da', 'fa fa-caret-right', 1, ' caret right'],
    ['&#xf0db', 'fa fa-columns', 1, ' columns'],
    ['&#xf0dc', 'fa fa-sort', 1, ' sort'],
    ['&#xf0dd', 'fa fa-sort-desc', 1, ' sort desc'],
    ['&#xf0de', 'fa fa-sort-asc', 1, ' sort asc'],
    ['&#xf0e0', 'fa fa-envelope', 1, ' envelope'],
    ['&#xf0e1', 'fa fa-linkedin', 1, ' linkedin'],
    ['&#xf0e2', 'fa fa-undo', 1, ' undo'],
    ['&#xf0e3', 'fa fa-gavel', 1, ' gavel'],
    ['&#xf0e4', 'fa fa-tachometer', 1, ' tachometer'],
    ['&#xf0e5', 'fa fa-comment-o', 1, ' comment o'],
    ['&#xf0e6', 'fa fa-comments-o', 1, ' comments o'],
    ['&#xf0e7', 'fa fa-bolt', 1, ' bolt'],
    ['&#xf0e8', 'fa fa-sitemap', 1, ' sitemap'],
    ['&#xf0e9', 'fa fa-umbrella', 1, ' umbrella'],
    ['&#xf0ea', 'fa fa-clipboard', 1, ' clipboard'],
    ['&#xf0eb', 'fa fa-lightbulb-o', 1, ' lightbulb o'],
    ['&#xf0ec', 'fa fa-exchange', 1, ' exchange'],
    ['&#xf0ed', 'fa fa-cloud-download', 1, ' cloud download'],
    ['&#xf0ee', 'fa fa-cloud-upload', 1, ' cloud upload'],
    ['&#xf0f0', 'fa fa-user-md', 1, ' user md'],
    ['&#xf0f1', 'fa fa-stethoscope', 1, ' stethoscope'],
    ['&#xf0f2', 'fa fa-suitcase', 1, ' suitcase'],
    ['&#xf0a2', 'fa fa-bell-o', 1, ' bell o'],
    ['&#xf0f4', 'fa fa-coffee', 1, ' coffee'],
    ['&#xf0f5', 'fa fa-cutlery', 1, ' cutlery'],
    ['&#xf0f6', 'fa fa-file-text-o', 1, ' file text o'],
    ['&#xf0f7', 'fa fa-building-o', 1, ' building o'],
    ['&#xf0f8', 'fa fa-hospital-o', 1, ' hospital o'],
    ['&#xf0f9', 'fa fa-ambulance', 1, ' ambulance'],
    ['&#xf0fa', 'fa fa-medkit', 1, ' medkit'],
    ['&#xf0fb', 'fa fa-fighter-jet', 1, ' fighter jet'],
    ['&#xf0fc', 'fa fa-beer', 1, ' beer'],
    ['&#xf0fd', 'fa fa-h-square', 1, ' h square'],
    ['&#xf0fe', 'fa fa-plus-square', 1, ' plus square'],
    ['&#xf100', 'fa fa-angle-double-left', 1, ' angle double left'],
    ['&#xf101', 'fa fa-angle-double-right', 1, ' angle double right'],
    ['&#xf102', 'fa fa-angle-double-up', 1, ' angle double up'],
    ['&#xf103', 'fa fa-angle-double-down', 1, ' angle double down'],
    ['&#xf104', 'fa fa-angle-left', 1, ' angle left'],
    ['&#xf105', 'fa fa-angle-right', 1, ' angle right'],
    ['&#xf106', 'fa fa-angle-up', 1, ' angle up'],
    ['&#xf107', 'fa fa-angle-down', 1, ' angle down'],
    ['&#xf108', 'fa fa-desktop', 1, ' desktop'],
    ['&#xf109', 'fa fa-laptop', 1, ' laptop'],
    ['&#xf10a', 'fa fa-tablet', 1, ' tablet'],
    ['&#xf10b', 'fa fa-mobile', 1, ' mobile'],
    ['&#xf10c', 'fa fa-circle-o', 1, ' circle o'],
    ['&#xf10d', 'fa fa-quote-left', 1, ' quote left'],
    ['&#xf10e', 'fa fa-quote-right', 1, ' quote right'],
    ['&#xf110', 'fa fa-spinner', 1, ' spinner'],
    ['&#xf111', 'fa fa-circle', 1, ' circle'],
    ['&#xf112', 'fa fa-reply', 1, ' reply'],
    ['&#xf113', 'fa fa-github-alt', 1, ' github alt'],
    ['&#xf114', 'fa fa-folder-o', 1, ' folder o'],
    ['&#xf115', 'fa fa-folder-open-o', 1, ' folder open o'],
    ['&#xf118', 'fa fa-smile-o', 1, ' smile o'],
    ['&#xf119', 'fa fa-frown-o', 1, ' frown o'],
    ['&#xf11a', 'fa fa-meh-o', 1, ' meh o'],
    ['&#xf11b', 'fa fa-gamepad', 1, ' gamepad'],
    ['&#xf11c', 'fa fa-keyboard-o', 1, ' keyboard o'],
    ['&#xf11d', 'fa fa-flag-o', 1, ' flag o'],
    ['&#xf11e', 'fa fa-flag-checkered', 1, ' flag checkered'],
    ['&#xf120', 'fa fa-terminal', 1, ' terminal'],
    ['&#xf121', 'fa fa-code', 1, ' code'],
    ['&#xf122', 'fa fa-reply-all', 1, ' reply all'],
    ['&#xf123', 'fa fa-star-half-o', 1, ' star half o'],
    ['&#xf124', 'fa fa-location-arrow', 1, ' location arrow'],
    ['&#xf125', 'fa fa-crop', 1, ' crop'],
    ['&#xf126', 'fa fa-code-fork', 1, ' code fork'],
    ['&#xf127', 'fa fa-chain-broken', 1, ' chain broken'],
    ['&#xf128', 'fa fa-question', 1, ' question'],
    ['&#xf129', 'fa fa-info', 1, ' info'],
    ['&#xf12a', 'fa fa-exclamation', 1, ' exclamation'],
    ['&#xf12b', 'fa fa-superscript', 1, ' superscript'],
    ['&#xf12c', 'fa fa-subscript', 1, ' subscript'],
    ['&#xf12d', 'fa fa-eraser', 1, ' eraser'],
    ['&#xf12e', 'fa fa-puzzle-piece', 1, ' puzzle piece'],
    ['&#xf130', 'fa fa-microphone', 1, ' microphone'],
    ['&#xf131', 'fa fa-microphone-slash', 1, ' microphone slash'],
    ['&#xf132', 'fa fa-shield', 1, ' shield'],
    ['&#xf133', 'fa fa-calendar-o', 1, ' calendar o'],
    ['&#xf134', 'fa fa-fire-extinguisher', 1, ' fire extinguisher'],
    ['&#xf135', 'fa fa-rocket', 1, ' rocket'],
    ['&#xf136', 'fa fa-maxcdn', 1, ' maxcdn'],
    ['&#xf137', 'fa fa-chevron-circle-left', 1, ' chevron circle left'],
    ['&#xf138', 'fa fa-chevron-circle-right', 1, ' chevron circle right'],
    ['&#xf139', 'fa fa-chevron-circle-up', 1, ' chevron circle up'],
    ['&#xf13a', 'fa fa-chevron-circle-down', 1, ' chevron circle down'],
    ['&#xf13b', 'fa fa-html5', 1, ' html5'],
    ['&#xf13c', 'fa fa-css3', 1, ' css3'],
    ['&#xf13d', 'fa fa-anchor', 1, ' anchor'],
    ['&#xf13e', 'fa fa-unlock-alt', 1, ' unlock alt'],
    ['&#xf140', 'fa fa-bullseye', 1, ' bullseye'],
    ['&#xf141', 'fa fa-ellipsis-h', 1, ' ellipsis h'],
    ['&#xf142', 'fa fa-ellipsis-v', 1, ' ellipsis v'],
    ['&#xf143', 'fa fa-rss-square', 1, ' rss square'],
    ['&#xf144', 'fa fa-play-circle', 1, ' play circle'],
    ['&#xf145', 'fa fa-ticket', 1, ' ticket'],
    ['&#xf146', 'fa fa-minus-square', 1, ' minus square'],
    ['&#xf147', 'fa fa-minus-square-o', 1, ' minus square o'],
    ['&#xf148', 'fa fa-level-up', 1, ' level up'],
    ['&#xf149', 'fa fa-level-down', 1, ' level down'],
    ['&#xf14a', 'fa fa-check-square', 1, ' check square'],
    ['&#xf14b', 'fa fa-pencil-square', 1, ' pencil square'],
    ['&#xf14c', 'fa fa-external-link-square', 1, ' external link square'],
    ['&#xf14d', 'fa fa-share-square', 1, ' share square'],
    ['&#xf14e', 'fa fa-compass', 1, ' compass'],
    ['&#xf150', 'fa fa-caret-square-o-down', 1, ' caret square o down'],
    ['&#xf151', 'fa fa-caret-square-o-up', 1, ' caret square o up'],
    ['&#xf152', 'fa fa-caret-square-o-right', 1, ' caret square o right'],
    ['&#xf153', 'fa fa-eur', 1, ' eur'],
    ['&#xf154', 'fa fa-gbp', 1, ' gbp'],
    ['&#xf155', 'fa fa-usd', 1, ' usd'],
    ['&#xf156', 'fa fa-inr', 1, ' inr'],
    ['&#xf157', 'fa fa-jpy', 1, ' jpy'],
    ['&#xf158', 'fa fa-rub', 1, ' rub'],
    ['&#xf159', 'fa fa-krw', 1, ' krw'],
    ['&#xf15a', 'fa fa-btc', 1, ' btc'],
    ['&#xf15b', 'fa fa-file', 1, ' file'],
    ['&#xf15c', 'fa fa-file-text', 1, ' file text'],
    ['&#xf15d', 'fa fa-sort-alpha-asc', 1, ' sort alpha asc'],
    ['&#xf15e', 'fa fa-sort-alpha-desc', 1, ' sort alpha desc'],
    ['&#xf160', 'fa fa-sort-amount-asc', 1, ' sort amount asc'],
    ['&#xf161', 'fa fa-sort-amount-desc', 1, ' sort amount desc'],
    ['&#xf162', 'fa fa-sort-numeric-asc', 1, ' sort numeric asc'],
    ['&#xf163', 'fa fa-sort-numeric-desc', 1, ' sort numeric desc'],
    ['&#xf164', 'fa fa-thumbs-up', 1, ' thumbs up'],
    ['&#xf165', 'fa fa-thumbs-down', 1, ' thumbs down'],
    ['&#xf166', 'fa fa-youtube-square', 1, ' youtube square'],
    ['&#xf167', 'fa fa-youtube', 1, ' youtube'],
    ['&#xf168', 'fa fa-xing', 1, ' xing'],
    ['&#xf169', 'fa fa-xing-square', 1, ' xing square'],
    ['&#xf16a', 'fa fa-youtube-play', 1, ' youtube play'],
    ['&#xf16b', 'fa fa-dropbox', 1, ' dropbox'],
    ['&#xf16c', 'fa fa-stack-overflow', 1, ' stack overflow'],
    ['&#xf16d', 'fa fa-instagram', 1, ' instagram'],
    ['&#xf16e', 'fa fa-flickr', 1, ' flickr'],
    ['&#xf170', 'fa fa-adn', 1, ' adn'],
    ['&#xf171', 'fa fa-bitbucket', 1, ' bitbucket'],
    ['&#xf172', 'fa fa-bitbucket-square', 1, ' bitbucket square'],
    ['&#xf173', 'fa fa-tumblr', 1, ' tumblr'],
    ['&#xf174', 'fa fa-tumblr-square', 1, ' tumblr square'],
    ['&#xf175', 'fa fa-long-arrow-down', 1, ' long arrow down'],
    ['&#xf176', 'fa fa-long-arrow-up', 1, ' long arrow up'],
    ['&#xf177', 'fa fa-long-arrow-left', 1, ' long arrow left'],
    ['&#xf178', 'fa fa-long-arrow-right', 1, ' long arrow right'],
    ['&#xf179', 'fa fa-apple', 1, ' apple'],
    ['&#xf17a', 'fa fa-windows', 1, ' windows'],
    ['&#xf17b', 'fa fa-android', 1, ' android'],
    ['&#xf17c', 'fa fa-linux', 1, ' linux'],
    ['&#xf17d', 'fa fa-dribbble', 1, ' dribbble'],
    ['&#xf17e', 'fa fa-skype', 1, ' skype'],
    ['&#xf180', 'fa fa-foursquare', 1, ' foursquare'],
    ['&#xf181', 'fa fa-trello', 1, ' trello'],
    ['&#xf182', 'fa fa-female', 1, ' female'],
    ['&#xf183', 'fa fa-male', 1, ' male'],
    ['&#xf184', 'fa fa-gittip', 1, ' gittip'],
    ['&#xf185', 'fa fa-sun-o', 1, ' sun o'],
    ['&#xf186', 'fa fa-moon-o', 1, ' moon o'],
    ['&#xf187', 'fa fa-archive', 1, ' archive'],
    ['&#xf188', 'fa fa-bug', 1, ' bug'],
    ['&#xf189', 'fa fa-vk', 1, ' vk'],
    ['&#xf18a', 'fa fa-weibo', 1, ' weibo'],
    ['&#xf18b', 'fa fa-renren', 1, ' renren'],
    ['&#xf18c', 'fa fa-pagelines', 1, ' pagelines'],
    ['&#xf18d', 'fa fa-stack-exchange', 1, ' stack exchange'],
    ['&#xf18e', 'fa fa-arrow-circle-o-right', 1, ' arrow circle o right'],
    ['&#xf190', 'fa fa-arrow-circle-o-left', 1, ' arrow circle o left'],
    ['&#xf191', 'fa fa-caret-square-o-left', 1, ' caret square o left'],
    ['&#xf192', 'fa fa-dot-circle-o', 1, ' dot circle o'],
    ['&#xf193', 'fa fa-wheelchair', 1, ' wheelchair'],
    ['&#xf194', 'fa fa-vimeo-square', 1, ' vimeo square'],
    ['&#xf195', 'fa fa-try', 1, ' try'],
    ['&#xf196', 'fa fa-plus-square-o', 1, ' plus square o'],
    ['&#xf197', 'fa fa-space-shuttle', 1, ' space shuttle'],
    ['&#xf198', 'fa fa-slack', 1, ' slack'],
    ['&#xf199', 'fa fa-envelope-square', 1, ' envelope square'],
    ['&#xf19a', 'fa fa-wordpress', 1, ' wordpress'],
    ['&#xf19b', 'fa fa-openid', 1, ' openid'],
    ['&#xf19c', 'fa fa-university', 1, ' university'],
    ['&#xf19d', 'fa fa-graduation-cap', 1, ' graduation cap'],
    ['&#xf19e', 'fa fa-yahoo', 1, ' yahoo'],
    ['&#xf1a0', 'fa fa-google', 1, ' google'],
    ['&#xf1a1', 'fa fa-reddit', 1, ' reddit'],
    ['&#xf1a2', 'fa fa-reddit-square', 1, ' reddit square'],
    ['&#xf1a3', 'fa fa-stumbleupon-circle', 1, ' stumbleupon circle'],
    ['&#xf1a4', 'fa fa-stumbleupon', 1, ' stumbleupon'],
    ['&#xf1a5', 'fa fa-delicious', 1, ' delicious'],
    ['&#xf1a6', 'fa fa-digg', 1, ' digg'],
    ['&#xf1a7', 'fa fa-pied-piper', 1, ' pied piper'],
    ['&#xf1a8', 'fa fa-pied-piper-alt', 1, ' pied piper alt'],
    ['&#xf1a9', 'fa fa-drupal', 1, ' drupal'],
    ['&#xf1aa', 'fa fa-joomla', 1, ' joomla'],
    ['&#xf1ab', 'fa fa-language', 1, ' language'],
    ['&#xf1ac', 'fa fa-fax', 1, ' x'],
    ['&#xf1ad', 'fa fa-building', 1, ' building'],
    ['&#xf1ae', 'fa fa-child', 1, ' child'],
    ['&#xf1b0', 'fa fa-paw', 1, ' paw'],
    ['&#xf1b1', 'fa fa-spoon', 1, ' spoon'],
    ['&#xf1b2', 'fa fa-cube', 1, ' cube'],
    ['&#xf1b3', 'fa fa-cubes', 1, ' cubes'],
    ['&#xf1b4', 'fa fa-behance', 1, ' behance'],
    ['&#xf1b5', 'fa fa-behance-square', 1, ' behance square'],
    ['&#xf1b6', 'fa fa-steam', 1, ' steam'],
    ['&#xf1b7', 'fa fa-steam-square', 1, ' steam square'],
    ['&#xf1b8', 'fa fa-recycle', 1, ' recycle'],
    ['&#xf1b9', 'fa fa-car', 1, ' car'],
    ['&#xf1ba', 'fa fa-taxi', 1, ' taxi'],
    ['&#xf1bb', 'fa fa-tree', 1, ' tree'],
    ['&#xf1bc', 'fa fa-spotify', 1, ' spotify'],
    ['&#xf1bd', 'fa fa-deviantart', 1, ' deviantart'],
    ['&#xf1be', 'fa fa-soundcloud', 1, ' soundcloud'],
    ['&#xf1c0', 'fa fa-database', 1, ' database'],
    ['&#xf1c1', 'fa fa-file-pdf-o', 1, ' file pdf o'],
    ['&#xf1c2', 'fa fa-file-word-o', 1, ' file word o'],
    ['&#xf1c3', 'fa fa-file-excel-o', 1, ' file excel o'],
    ['&#xf1c4', 'fa fa-file-powerpoint-o', 1, ' file powerpoint o'],
    ['&#xf1c5', 'fa fa-file-image-o', 1, ' file image o'],
    ['&#xf1c6', 'fa fa-file-archive-o', 1, ' file archive o'],
    ['&#xf1c7', 'fa fa-file-audio-o', 1, ' file audio o'],
    ['&#xf1c8', 'fa fa-file-video-o', 1, ' file video o'],
    ['&#xf1c9', 'fa fa-file-code-o', 1, ' file code o'],
    ['&#xf1ca', 'fa fa-vine', 1, ' vine'],
    ['&#xf1cb', 'fa fa-codepen', 1, ' codepen'],
    ['&#xf1cc', 'fa fa-jsfiddle', 1, ' jsfiddle'],
    ['&#xf1cd', 'fa fa-life-ring', 1, ' life ring'],
    ['&#xf1ce', 'fa fa-circle-o-notch', 1, ' circle o notch'],
    ['&#xf1d0', 'fa fa-rebel', 1, ' rebel'],
    ['&#xf1d1', 'fa fa-empire', 1, ' empire'],
    ['&#xf1d2', 'fa fa-git-square', 1, ' git square'],
    ['&#xf1d3', 'fa fa-git', 1, ' git'],
    ['&#xf1d4', 'fa fa-hacker-news', 1, ' hacker news'],
    ['&#xf1d5', 'fa fa-tencent-weibo', 1, ' tencent weibo'],
    ['&#xf1d6', 'fa fa-qq', 1, ' qq'],
    ['&#xf1d7', 'fa fa-weixin', 1, ' weixin'],
    ['&#xf1d8', 'fa fa-paper-plane', 1, ' paper plane'],
    ['&#xf1d9', 'fa fa-paper-plane-o', 1, ' paper plane o'],
    ['&#xf1da', 'fa fa-history', 1, ' history'],
    ['&#xf1db', 'fa fa-circle-thin', 1, ' circle thin'],
    ['&#xf1dc', 'fa fa-header', 1, ' header'],
    ['&#xf1dd', 'fa fa-paragraph', 1, ' paragraph'],
    ['&#xf1de', 'fa fa-sliders', 1, ' sliders'],
    ['&#xf1e0', 'fa fa-share-alt', 1, ' share alt'],
    ['&#xf1e1', 'fa fa-share-alt-square', 1, ' share alt square'],
    ['&#xf1e2', 'fa fa-bomb', 1, ' bomb']
]
tinyMCEPopup.onInit.add(function() {
    tinyMCEPopup.dom.show("jce"), tinyMCEPopup.dom.setHTML("charmapView", renderCharMapHTML())
});