<?php 

/**
 * Joomla! 1.5 component myextension
 * Code generated by : Danny's Joomla! 1.5 MVC Component Code Generator (v 0.7 beta )
 * http://www.joomlafreak.be
 * date generated:  
 * @package myextension
 * @license GNU Public License (because open source matters...)
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );



jimport('joomla.application.component.view');
/**
  * HTML View class for the myextension component
  * @package Myextension
  */
class CCKjSeblodViewShipping extends JView{
	function display( $tpl = null ){
		
		// Get Request Vars
		global $mainframe, $option;
		
		$model 		=&	$this->getModel();

		$user 		=&	JFactory::getUser();
		$document	=&	JFactory::getDocument();
		
		$menus		=	&JSite::getMenu();
		$menu 		=	$menus->getActive();
		$view		=	JRequest::getVar('view');
		
		if ( is_object( $menu ) ) {
			$menu_params	=	new JParameter( $menu->params );
		}
		
		
		
		if($view){
			parent::display();
		}else{
			parent::display($view);
		}
	}
	
	
}